# Configuration file for combine_files installation
# Format:
# - file: filename
#   executable: true/false (optional, default false)
#   destination: subdirectory (optional, default is root of install_dir)

- file: combine_files.sh
  executable: true
- file: combine_files.py
- file: README.md
  destination: docs
